### ISSUE TITLE
Missing create_C-RVDB.py

### ISSUE THREAD

**Issue by jebard** [ArifaKhanLab/RVDB#1]
Hello! Is the create_C-RVDB script available? Thanks!

I also noticed that the download links on https://hive.biochemistry.gwu.edu/rvdb/ are all broken.

Thanks,
Jonathan

**Comment by ArifaKhanLab** [comment]
Hi jebard,
Sorry for the extremely late reply. The create_C-RVDB is uploaded as request.
GW HIVE encountered server problem few weeks ago and everything should be up right now. 

Thanks for using RVDB!

RVDB Team
