### ISSUE TITLE
The script "prep_manual_review.py" tries to imports a function that does not exist in "sequence_record_functions_PIPE"

### ISSUE THREAD

**Issue by onabluemoon** [ArifaKhanLab/RVDB#3]
I am following the instructions to update RVDB and I have reached the point where I should run the "prep_manual_review.py" script, however this script requires importing a function from "sequence_record_functions_PIPE"  that does not exist either in the provided version of this file nor in any version that can be found on your git.  
  

>   File "prep_manual_review.py", line 5, in <module>
    from sequence_record_functions_PIPE import get_filenames as getfns
ImportError: cannot import name get_filenames

**Comment by ArifaKhanLab** [comment]
The path of library is updated. Please re-install the pipeline with the updated scripts.

**Comment by JonathonMifsud** [comment]
Hi, sorry to comment on a closed issue but I am running into a similar problem with RVDB_characterization.py on Linux 

`Traceback (most recent call last):
  File "./scripts/RVDB_characterization.py", line 354, in <module>
    from sequence_record_functions_PIPE import get_accs_flatfile as getaccs
ImportError: No module named sequence_record_functions_PIPE`

Any suggestions would be greatly appreciated!

**Comment by ArifaKhanLab** [comment]
Hi JonathonMifsud,

Can you please confirm that you are running Python 2?

**Comment by JonathonMifsud** [comment]
Thank you for the reply, yes I am running the script with Python2. It looks like the error was my fault and down to a pathing problem to the additional scripts.
