### ISSUE TITLE
RVDB release 16.0 SQL file is FASTA format file

### ISSUE THREAD

**Issue by peterk87** [ArifaKhanLab/RVDB#4]
The [U-RVDBv16.0.sqlite.db] file from the [RVDB] website isn't a SQL file and contains FASTA sequences instead.

```
$ wget https://hive.biochemistry.gwu.edu/prd/rvdb//content/U-RVDBv16.0.sqlite.db
$ head -n1 U-RVDBv16.0.sqlite.db
>NC_001798.2 Human herpesvirus 2 strain HG52, complete genome
$ tail -n1 U-RVDBv16.0.sqlite.db
TGGTATCAGAGCCAAGTGCTCGTAACCTCCC....
```

[RVDB]: https://hive.biochemistry.gwu.edu/rvdb
[U-RVDBv16.0.sqlite.db]: https://hive.biochemistry.gwu.edu/prd/rvdb//content/U-RVDBv16.0.sqlite.db

**Comment by a7032018** [comment]
Please note that new RVDB site is moved to https://rvdb.dbi.udel.edu/
