### ISSUE TITLE
RVDB v16.0 most sequence contain date in FASTA header instead of sequence description

### ISSUE THREAD

**Issue by peterk87** [ArifaKhanLab/RVDB#5]
Of the 2,820,860 sequences in the v16.0 FASTA file, 2,811,816 have headers with what appears to be a date like `25-AUG-2016` instead of the virus name or description. Only around 9044 sequences have what appear to be regular names.  

For example:

```
>AB504233.1 25-AUG-2016
```

has the name `Sapovirus Tamagawa River/Site2_a/Nov2003/JP gene for capsid protein, partial cds` (https://www.ncbi.nlm.nih.gov/nuccore/AB504233.1). I'm not sure where the `25-AUG-2016` comes from.

**Comment by a7032018** [comment]
The date 25-AUG-2016 is the release date for the record. The original fasta header downloaded from GenBank FTP contains this info
